config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  devise_for :users
  resources :literatures
  resources :courses

  #resources :courses do
  #  resources :sessions
  #end

  root 'static_pages#welcome'
  get '/preview', to: 'static_pages#preview'
  #get '/patients/:id', to: 'patients#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/literature.rb
class Literature < ApplicationRecord
  belongs_to :meeting
  has_one_attached :attachment
end

app/controllers/literatures_controller.rb
class LiteraturesController < ApplicationController
  before_action :set_literature, only: [:show, :edit, :update, :destroy]

  # GET /literatures
  # GET /literatures.json
  def index
    @literatures = Literature.all
  end

  # GET /literatures/1
  # GET /literatures/1.json
  def show
  end

  # GET /literatures/new
  def new
    @literature = Literature.new
  end

  # GET /literatures/1/edit
  def edit
  end

  # POST /literatures
  # POST /literatures.json
  def create
    @literature = Literature.new(literature_params)
    @meeting = @literature.meeting

    respond_to do |format|
      if @literature.save
        format.html { redirect_to @literature, notice: 'Literature was successfully created.' }
        format.json { render :show, status: :created, location: @literature }
        format.js { render 'courses/reload-literature.js.erb' }
      else
        format.html { render :new }
        format.json { render json: @literature.errors, status: :unprocessable_entity }
        format.js {'courses/reload-literature.js.erb'}
      end
    end
  end

  # PATCH/PUT /literatures/1
  # PATCH/PUT /literatures/1.json
  def update
    respond_to do |format|
      if @literature.update(literature_params)
        format.html { redirect_to @literature, notice: 'Literature was successfully updated.' }
        format.json { render :show, status: :ok, location: @literature }
      else
        format.html { render :edit }
        format.json { render json: @literature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /literatures/1
  # DELETE /literatures/1.json
  def destroy
    @literature.destroy
    respond_to do |format|
      format.html { redirect_to literatures_url, notice: 'Literature was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_literature
      @literature = Literature.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def literature_params
      params.require(:literature).permit(:title, :meeting_id, :attachment)
    end
end

app/helpers/literatures_helper.rb
module LiteraturesHelper
end

app/views/literatures/_form.html.erb
<%= simple_form_for(@literature) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/literatures/edit.html.erb
<h1>Editing Literature</h1>

<%= render 'form', literature: @literature %>

<%= link_to 'Show', @literature %> |
<%= link_to 'Back', literatures_path %>

app/views/literatures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Literatures</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @literatures.each do |literature| %>
      <tr>
        <td><%= literature.title %></td>
        <td><%= link_to 'Show', literature %></td>
        <td><%= link_to 'Edit', edit_literature_path(literature) %></td>
        <td><%= link_to 'Destroy', literature, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Literature', new_literature_path %>

app/views/literatures/new.html.erb
<h1>New Literature</h1>

<%= render 'form', literature: @literature %>

<%= link_to 'Back', literatures_path %>

app/views/literatures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @literature.title %>
</p>

<%= link_to 'Edit', edit_literature_path(@literature) %> |
<%= link_to 'Back', literatures_path %>