config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  devise_for :users
  resources :literatures
  resources :courses

  #resources :courses do
  #  resources :sessions
  #end

  root 'static_pages#welcome'
  get '/preview', to: 'static_pages#preview'
  #get '/patients/:id', to: 'patients#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    #@new_meeting = @course.meetings.build
    @meeting = Meeting.new(course: @course)
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create

    @course = Course.new(course_params)
    #@course.avatar.attach(params[:avatar])
    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:title, :description, :avatar, :semester, meetings_attributes: [ :topic, :description, :date])
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :semester %>
    <%= form.text_field :semester %>
  </div>

  <div class="field">
  <%= form.label :avatar %>
  <%= form.file_field :avatar %>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/_form_for_literature.html.erb
<div class="m-4">
<%= simple_form_for Literature.new, remote:true do |f| %>

    <%= f.input :title %>
    <%= f.input :attachment %>
    <br>

    <%= f.hidden_field :meeting_id, value: meeting.id %>

    <%= f.button :submit, "Create", class: "btn btn-success btn-lg" %>
<% end %>

</div>

app/views/courses/_form_for_meeting.html.erb
<%#= form_with (model: [course, meeting], local: true) do |form| %>
<%#= form_with(model: [course, meeting], url: [course, meeting], local: true) do |form| %>
<div class="m-4">
<%= simple_form_for meeting, remote:true do |f| %>

    <%= f.input :topic %>
    <%= f.input :type_of_meeting, collection: Rails.configuration.types_of_meeting %>
    <%= f.input :description %>
    <%= f.input :date, order: [:day, :month, :year] %>

    <%= f.hidden_field :course_id, value: course.id %>

    <%= f.file_field :video %>
    <br>
    <br>
    <%= f.button :submit, "Create", class: "btn btn-success btn-lg" %>
<% end %>

</div>

app/views/courses/_literature.html.erb
<div class="alert alert-dark" role="alert">
  Zu Lesende Literatur:
</div>

<% meeting.literatures.each do |literature| %>
<div class="row">
  <div class="col-4">
    <% if literature.attachment.attached? %>

      <% if literature.attachment.previewable? %>
        <%= link_to rails_blob_path(literature.attachment, disposition: "attachment"), class: "btn btn-light" do %>
          <%= image_tag literature.attachment.preview(resize: "500"), class: "img-fluid" %><br>
        <% end %>
      <% else %>
        <%= fa_icon "file" %>
      <% end %>

      <% else %>

      <%= fa_icon "file" %>

    <% end %>
  </div>
  <div class="col-8">
    <p>
      <%= literature.title %>
    </p>
    <hr>
    <% if literature.attachment.attached? %>
    <%= link_to rails_blob_path(literature.attachment, disposition: "attachment"), class: "btn btn-light" do %>
      <%= fa_icon "download" %>
      <% end %>

      <% else %>
      <button type="button" class="btn btn-light"><%= fa_icon "download" %></button>
    <% end %>
  </div>
</div>

<hr>
<% end %>

<% if user_signed_in? && current_user.is_admin? %>
      <%= render 'courses/form_for_literature', meeting: meeting %>
<% end %>

app/views/courses/_meeting.html.erb
<div class="tab-content" id="nav-tabContent">
  <% course.meetings.order(:date).each_with_index do |meeting, i| %>
    <% if i == 0 %>

      <div class="tab-pane fade show active" id="list-<%= meeting.id %>" role="tabpanel" aria-labelledby="list-profile-list">
    <% else %>

    <div class="tab-pane fade" id="list-<%= meeting.id %>" role="tabpanel" aria-labelledby="list-profile-list">
    <% end %>
      <div class="card mb-3">
        <div class="embed-responsive embed-responsive-16by9">
          <% if meeting.video.attached? %>
            <%= video_tag rails_blob_path(meeting.video), :class => "embed-responsive", :controls => true %>
          <% else %>
              <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/L9AkpdVtK9A" allowfullscreen></iframe>
          <% end %>
        </div>
        <div class="card-body">
          <h2 class="card-title"><%= meeting.topic %></h2>
          <h6 class="card-subtitle mb-2 text-muted"><%= meeting.type_of_meeting %></h6>
          <p class="card-text"><%= sanitize meeting.description %></p>
          <p class="card-text"><small class="text-muted"><b>Datum: </b><%= meeting.date.strftime("%d-%m-%Y") %></small></p>
          <hr>


          <div id="literature-<%=meeting.id %>">
            <%= render 'courses/literature', meeting: meeting %>
          </div>

            <%#= link_to 'Destroy', literature_path(literature), method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
  </div>
  <% end %>

  <div class="tab-pane fade" id="list-new" role="tabpanel" aria-labelledby="list-profile-list">
    <div class="card mb-3">

      <div class="card-body">
        <%= render "courses/form_for_meeting", course: course, meeting: meeting %>
      </div>
    </div>
</div>

  </div>

</div>

app/views/courses/_navigation.html.erb
<nav class="navbar navbar-light navbar-expand-md bg-logo justify-content-center">
  <%= link_to root_path, class: "navbar-brand d-flex w-50 mr-auto" do %>
      <%= image_tag("ousia-owl.png", class: "img-fluid", style: "height: 75px;") %>
  <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsingNavbar3">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse w-100" id="collapsingNavbar3">
        <ul class="navbar-nav w-100 justify-content-center">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= @course.title %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item">
            <%= link_to "Meine Kurse", root_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Meine Noten", root_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Übersicht", root_path, class:"nav-link" %>
          </li>
        </ul>
        <ul class="nav navbar-nav ml-auto w-100 justify-content-end">
          <% if user_signed_in? %>
              <li class="nav-item hidden-xl-down">
                <div class="navbar-brand"><%= current_user.email %></div>
              </li>
              <li class="nav-item">
                <%= link_to 'Edit profile', edit_user_registration_path, :class => 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'nav-link'  %>
              </li>
          <% else %>
              <li class="nav-item">
                <%= link_to "Sign up", new_user_registration_path, :class => 'nav-link'  %>
              </li>
              <li class="nav-item">
                <%= link_to "Login", new_user_session_path, :class => 'nav-link'  %>
              </li>
          <% end %>
        </ul>
    </div>
</nav>

app/views/courses/_sideoverview.html.erb
<div class="list-group" id="list-tab" role="tablist">
  <a class="list-group-item text-center">
    <h3>Übersicht</h3>
  </a>

  <% if user_signed_in? && current_user.is_admin? %>
        <a class="list-group-item list-group-item-action flex-column align-items-start" id="list-home-list" data-toggle="list" href="#list-new" role="tab" aria-controls="home">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1"> <%= fa_icon "plus" %> Sitzung hinzufügen</h5>
          </div>
        </a>
  <% end %>

  <% course.meetings.order(:date).each_with_index do |meeting, i| %>
  <% if i == 0 %>

    <a class="list-group-item list-group-item-action flex-column align-items-start active" id="list-home-list" data-toggle="list" href="#list-<%= meeting.id %>" role="tab" aria-controls="home">
  <% else %>

    <a class="list-group-item list-group-item-action flex-column align-items-start" id="list-home-list" data-toggle="list" href="#list-<%= meeting.id %>" role="tab" aria-controls="home">
  <% end %>

    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1"><%= meeting.topic %></h5>
    </div>
    <p class="text-muted"><%= meeting.type_of_meeting %></p>
    <p class="mb-1"><%= fa_icon "calendar" %> <%= meeting.date.strftime("%d-%m-%Y") %></p>
  </a>
  <% end %>

</div>

app/views/courses/_top.html.erb
<div class="container mt-2">
  <div class="card mb-3">
    <% if course.avatar.attached? %>

        <%= image_tag course.avatar, class: "card-img-top" %>
        <% else %>
        <img class="card-img-top" src="https://lorempixel.com/480/680/" alt="Card image cap">
    <% end %>
    <div class="card-body">
      <h1 class="card-title"><%= course.title %></h1>
      <p class="card-text"><%= course.description %></p>
      <p class="card-text"><small class="text-muted"><strong>Semester:</strong> <%= course.semester %></small></p>
    </div>
  </div>
</div>

app/views/courses/ablage.html.erb
<nav class="navbar navbar-expand-sm navbar-light mb-4 bg-logo">
  <%= link_to root_path do %>
      <%= image_tag("ousia-owl.png", class: "img-fluid", style: "height: 75px;") %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= @course.title %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <%= link_to "Meine Kurse", root_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Meine Noten", root_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Übersicht", root_path, class:"nav-link" %>
      </li>
    </ul>

  </div>
</nav>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/reload-literature.js.erb
$( "#literature-<%= @meeting.id %>" ).fadeOut( "slow", function() {

    x = $("<%= escape_javascript( render "courses/literature/", meeting: @meeting) %>")

    $("#literature-<%= @meeting.id %>").empty().append(x).fadeIn("slow");

});

app/views/courses/reload-meeting.js.erb
$("#sideoverview").fadeOut("slow", function(){

  x = $("<%= escape_javascript( render "courses/sideoverview", course: @course) %>")

  $("#sideoverview").empty().append(x).fadeIn("slow", function(){
      $('a[href="#list-<%= @meeting.id %>"]').tab('show');
  });


});

$( "#meeting" ).fadeOut( "slow", function() {

    x = $("<%= escape_javascript( render "courses/meeting", course: @course, meeting: @new_meeting) %>")

    $("#meeting").empty().append(x).fadeIn("slow");
});

app/views/courses/show.html.erb
<%= render "navigation" %>

<%= flash_messages %>

<%= render "top", course: @course %>

<div class="container">
  <div class="row">
    <div class="col-4">
      <div id="sideoverview">
        <%= render "sideoverview", course: @course %>
      </div>

    </div>
    <div class="col-8">
      <div id="meeting">
        <%= render "meeting", course: @course, meeting: @meeting %>
      </div>
  </div>
</div>
</div>